[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "frame-ancestors 'self' https://memegenes.com https://www.youtube.com"

[[edge_functions]]
  function = "hello" 
  path = "/hello"